import 'dart:async';
import 'package:test/test.dart';
import 'package:path/path.dart' as p;
import 'package:claudart/commands/add.dart';
import 'package:claudart/registry.dart';
import 'package:claudart/paths.dart';
import '../helpers/mocks.dart';

const _projectRoot = '/projects/my-app';
const _memoryRoot = '/fake-home/.claude/projects';

class _ExitException implements Exception {
  final int code;
  const _ExitException(this.code);
}

Never _throwExit(int code) => throw _ExitException(code);

MemoryFileIO _emptyIO() => MemoryFileIO();

/// Returns canned answers in call order: project name, SDK constraint,
/// project type. `null` means "accept the default".
String? Function(String, {String? defaultValue}) _prompts(
    List<String?> answers) {
  var i = 0;
  return (q, {defaultValue}) {
    final a = i < answers.length ? answers[i] : null;
    i++;
    return a ?? defaultValue;
  };
}

/// Returns canned answers in call order: usesDartrix, githubTracking,
/// mermaidDiagrams, changelogEnabled.
bool Function(String) _confirms(List<bool> answers) {
  var i = 0;
  return (q) => i < answers.length ? answers[i++] : false;
}

void main() {
  group('add — new workspace scaffold', () {
    test('writes PLAN.md at the project root', () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', '>=3.5.0 <4.0.0', 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      final plan = io.read(p.join(_projectRoot, 'PLAN.md'));
      expect(plan, contains('my-app — plan'));
    });

    test('writes CLAUDE.md at the project root, with SDK constraint', () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', '>=3.5.0 <4.0.0', 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      final claudeMd = io.read(claudeMdPathFor(_projectRoot));
      expect(claudeMd, contains('## Generated by claudart link'));
      expect(claudeMd, contains('Dart SDK: `>=3.5.0 <4.0.0`'));
    });

    test('omits Flutter constraint when project type is not flutter', () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', '>=3.5.0 <4.0.0', 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      final claudeMd = io.read(claudeMdPathFor(_projectRoot));
      expect(claudeMd, isNot(contains('Flutter:')));
    });

    test('includes Flutter constraint when project type is flutter', () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', '>=3.19.0 <4.0.0', 'flutter']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      final claudeMd = io.read(claudeMdPathFor(_projectRoot));
      expect(claudeMd, contains('Flutter: `>=3.19.0 <4.0.0`'));
    });

    test('adds a registry entry', () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', null, 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      final entry = Registry.load(io: io).findByName('my-app');
      expect(entry, isNotNull);
      expect(entry!.projectRoot, equals(_projectRoot));
      expect(entry.workspacePath, equals(workspaceFor('my-app')));
    });

    test('scaffolds an empty archive/ delta record with a .gitkeep and README',
        () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', null, 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      expect(
          io.fileExists(p.join(_projectRoot, 'archive', '.gitkeep')), isTrue);
      final readme = io.read(p.join(_projectRoot, 'archive', 'README.md'));
      expect(readme, contains('delta record'));
    });

    test('creates the .claude symlink', () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', null, 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      expect(io.linkExists(p.join(_projectRoot, '.claude')), isTrue);
    });

    test(
        'includes the dartrix coverage-gaps section when usesDartrix is confirmed',
        () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', null, 'cli']),
        confirmFn: _confirms([true, false, false, false]),
        exitFn: _throwExit,
      );
      final plan = io.read(p.join(_projectRoot, 'PLAN.md'));
      expect(plan, contains('dartrix coverage gaps'));
    });

    test(
        'registers a memory file under the (overridden) Claude Code memory root',
        () async {
      final io = _emptyIO();
      await runAdd(
        io: io,
        projectRootOverride: _projectRoot,
        claudeMemoryRootOverride: _memoryRoot,
        promptFn: _prompts(['my-app', null, 'cli']),
        confirmFn: _confirms([false, false, false, false]),
        exitFn: _throwExit,
      );
      final hash = _projectRoot.replaceAll('/', '-');
      final memoryDir = p.join(_memoryRoot, hash, 'memory');
      expect(io.fileExists(p.join(memoryDir, 'project_my-app.md')), isTrue);
      final index = io.read(p.join(memoryDir, 'MEMORY.md'));
      expect(index, contains('my-app'));
    });

    test('prints which project it scaffolded before finishing', () async {
      final io = _emptyIO();
      final output = <String>[];
      await runZoned(
        () => runAdd(
          io: io,
          projectRootOverride: _projectRoot,
          claudeMemoryRootOverride: _memoryRoot,
          promptFn: _prompts(['my-app', null, 'cli']),
          confirmFn: _confirms([false, false, false, false]),
          exitFn: _throwExit,
        ),
        zoneSpecification: ZoneSpecification(
          print: (_, __, ___, line) => output.add(line),
        ),
      );
      expect(output.join('\n'), contains('Scaffolded: my-app'));
    });
  });
}
