// claude_template.dart — CLAUDE.md's machine-owned tail section
//
// Pure function, no I/O — relocated from lib/knowledge_templates.dart
// (formerly claudeMdTemplate), where it had zero call sites. Wired into
// link.dart so `claudart link` actually regenerates this section, as its
// own header text has always claimed it would.
//
// Output starts with the `## Generated by claudart link` heading —
// NOT a full document. It is spliced onto the end of an existing
// CLAUDE.md (link.dart preserves everything above the marker), never
// written as a whole file on its own.

String claudeTemplate({
  required String workspacePath,
  required String projectName,
  required List<String> genericFiles,
  String? sdkConstraint,
  String? flutterConstraint,
}) {
  final genericSection = genericFiles.isEmpty
      ? ''
      : '''### Generic practices
${genericFiles.map((f) => '- $workspacePath/knowledge/generic/$f').join('\n')}

''';

  final envLines = StringBuffer();
  if (sdkConstraint != null || flutterConstraint != null) {
    envLines.writeln('\n## Environment\n');
    if (sdkConstraint != null) envLines.writeln('- Dart SDK: `$sdkConstraint`');
    if (flutterConstraint != null) {
      envLines.writeln('- Flutter: `$flutterConstraint`');
    }
    envLines.writeln(
        '\nDo not suggest APIs or syntax unavailable within these constraints.');
    envLines.writeln('\n---');
  }

  return '''## Generated by claudart link | Project: $projectName
> Re-run `claudart link` to regenerate environment section below.
> Profile, document hierarchy, and constraints above are manually maintained.

## Workflow protocol

Always follow this order — no exceptions:
1. **Verify** — read the relevant files, understand current state
2. **Plan** — state what you intend to do before writing code. If multiple approaches exist, surface them. If uncertain, ask.
3. **Test** — run safely
4. **Confirm** — present result, wait for user confirmation
5. **Commit** — only after confirmed

Never commit before testing. Never skip confirmation.

---
$envLines
## Knowledge base

Read the following files at the start of every session before doing anything else.

$genericSection### Project context
- $workspacePath/knowledge/projects/$projectName.md

### Session state
- $workspacePath/handoff.md
- $workspacePath/skills.md

---

## Git rules

- **Never push to remote** under any circumstances without explicit confirmation
- Local commits only, and only when explicitly requested
''';
}
